### ISSUE TITLE
GSE161918

### ISSUE THREAD

**Issue by Mimianmy** [Kang-chen/data_pipeline#12]
**Source ID**
GSE161918

**Bugs Detail**

Step X: The bug occurred during the execution of the Python script DataExtract.py in the data pipeline process.
Key Error: The key error encountered was an IndexError indicating that index 0 is out of bounds for axis 0 with size 0. This error occurred when the script attempted to access the first element of an empty array or list (gene_names[0]) in the identify_species function.

**Steps to Reproduce**

Step 1: Run the download_xlsx.sh script to download the necessary files.
Step 2: Activate the conda environment 'lamindb' and run the Python script DataExtract.py.
Step 3: The script processes the downloaded files, including H5 files, and attempts to convert gene symbols to Ensembl IDs.

**Possible Solution**

The error suggests that the gene_names list is empty when the script tries to access its first element. This could be due to several reasons such as incorrect file paths, missing data in the files, or issues with the way data is being read into the script. Here are some steps to troubleshoot and potentially resolve the issue:

1. Verify that the H5 files are correctly downloaded and contain the expected data.
2. Check the file paths and ensure that the script is reading the correct files.
3. Add error handling to check if gene_names is empty before attempting to access its elements. If it is empty, the script should handle this gracefully, perhaps by logging a warning and skipping the current file or providing a default value.
4. If the issue is due to missing data, ensure that the data extraction process is correctly implemented and that the expected data is present in the source files.
5. Review the logic in the identify_species function to ensure that it correctly identifies the species based on the gene names. If the species identification relies on specific prefixes (like "ENSG" or "ENSMUS"), make sure these prefixes are present in the data.

**Comment by Kang-chen** [comment]
@gefujing Could you help reproduce the issue and see how we can fix it?

**Comment by gefujing** [comment]
Hi, anying, kang,
I have tested this dataset and found the error message is:

```
Activating conda environment 'lamindb'...
Running Python script DataExtract.py...
Downloaded: All GSE161918 files.
Extraction complete for GSE161918_RAW.tar.
Extraction complete for GSE161918_demuxletResults.tar.gz.
H5 files detected, processing with read_and_merge_h5_files...
Reading GSM4929065_B1_10xlane1_CSP_filtered_feature_bc_matrix.h5...
Traceback (most recent call last):
  File "/home/fujing/fujingge/data_pipeline/python/dataextract.py", line 674, in <module>
    adata = auto_detect_and_process_files(output_dir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fujing/fujingge/data_pipeline/python/dataextract.py", line 613, in auto_detect_and_process_files
    adata_h5 = read_and_merge_h5_files(output_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fujing/fujingge/data_pipeline/python/dataextract.py", line 381, in read_and_merge_h5_files
    adata = convert_symbol_to_ensembl(adata)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fujing/fujingge/data_pipeline/python/dataextract.py", line 199, in convert_symbol_to_ensembl
    species = identify_species(adata)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fujing/fujingge/data_pipeline/python/dataextract.py", line 157, in identify_species
    is_symbol = not gene_names[0].startswith("ENSG") and not gene_names[0].startswith("ENSMUS")
                    ~~~~~~~~~~^^^
  File "/home/fujing/miniconda3/envs/lamindb/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
           ^^^^^^^^^^^^
IndexError: index 0 is out of bounds for axis 0 with size 0
Error in step 3: Python script dataextract.py execution failed.
```

This means that the data can be downloaded, unzipped and read. However, errors occur in _**convert_symbol_to_ensembl**_ function, especially in the _**is_symbol**_ function.

You can simply read the identified h5 files on the **_jupyter notebook_** and check if the file format is standard. For example, there is no gene information in these h5 files, which means there is a problem with the source file.


```
import scanpy as sc
import pandas as pd
adata = sc.read_10x_h5("../data_pipeline/workdir/geo_supp_files/GSM4929065_B1_10xlane1_CSP_filtered_feature_bc_matrix.h5")
adata
-----------------------
AnnData object with n_obs × n_vars = 30000 × 0
    var: 'gene_ids', 'feature_types', 'genome', 'pattern', 'read', 'sequence'
```

You can check the **_geo_supp_files_** folder in the **_workdir_**, which stores all the files downloaded from the GSExxx. For this dataset, the sequencing information that can be used may be stored in **_GSE161918_AllBatches_SeuratObj.rds.gz_**. However, in our pipeline, there is no RDS data reading function. Therefore, I recommend discarding this dataset.

**Note:** Before you test the next dataset, you should **manually delete the geo_supp_files folder**, otherwise incorrect data will continue to be saved.

**Comment by Kang-chen** [comment]
@Mimianmy Please review the description above. 

The issue is caused by the h5 file from GSE161918 not containing any gene data. To prevent runtime errors and skip such faulty files, you could consider adding a try-catch block and validating the file content before processing.

**Comment by Mimianmy** [comment]
@gefujing @Kang-chen  Thank you for your detailed explanation regarding the issue with the GSE161918 dataset!:) It seemed that h5 files from GSE152058 also contains some problem. I will follow your suggestion to implement a try-catch block in the pipeline to handle such faulty files gracefully and skip them if necessary～
